### ISSUE TITLE
Ensure dotenv is installed

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomla-composer#15]
When working on a joomla-platform codebase that also requires joomla extensions installed using our [joomlatools/installer plugin](https://github.com/joomlatools/joomla-composer), the installation will fail when joomlatools/installer bootstraps the platform:

* composer finds a package of type `joomla-installer` and will also require joomlatools/installer
* joomlatools/installer gets installed first 
* the joomlatools/installer plugin tries to bootstrap the platform but fails because the basic platform dependencies are not installed (and not loaded via autoload) yet

**Comment by stevenrombauts** [comment]
Attempted solution: try to install the platform dependencies first from inside the joomlatools/installer plugin. This is not possible using Composer.

Proposed solution: use two Composer manifests:

* `composer.json` = the default (platform) dependencies. Install these first using `composer install`
* `project.json` = a Composer manifest that lists the secondary packages (extensions, modules, ..). Install these afterwards using `COMPOSER=project.json composer install`.

Moving this issue to backlog.

**Comment by johanjanssens** [comment]
@stevenrombauts The problem here only is the phpdotenv library which is not available. We could ship this library as part of the platform and include it into the /libraries folder. This would solve out without too much additional complexities

**Comment by stevenrombauts** [comment]
@johanjanssens The only other solution is patching Composer to support package ordering (which is very complex) so our best bet is to include it by default, yes.

**Comment by johanjanssens** [comment]
@stevenrombauts Agreed, i'll work on including phpdotenv instead. Shall we close this issue here ?

**Comment by stevenrombauts** [comment]
Agreed, closing this ticket!
